### ISSUE TITLE
Can't load Autoroom.

### ISSUE THREAD

**Issue by Fabian-Evolved** [PhasecoreX/PCXCogs#109]
Hi i'm trying to load AutoRoom on Red 3.5.1

But the following error shows in console upon loading it.

https://prnt.sc/4Q1bu0PU5_Yh

Thanks in advance!

**Comment by Fabian-Evolved** [comment]
Python 3.8.10

**Comment by PhasecoreX** [comment]
Yeah, sorry about that. I think there's a way to install an older version of cogs based on commit hash, I'm just not sure how... Of course, those older versions won't get any new updates either.
