### ISSUE TITLE
[FEATURE] autoroom: Add variable to ping the creator of an autoroom

### ISSUE THREAD

**Issue by IceFlom** [PhasecoreX/PCXCogs#111]
Texts sent to the chat of the voice channel are hardly visible. If you don't know it, you don't realize that something was written there. 

Therefore, it would be good if you could ping the creator of the voice channel for the initial text that can be sent in an autoroom.
Similar to the {{username}} variable, another variable to ping the user would be helpful.

**Comment by PhasecoreX** [comment]
Added with 1004f01, it's `{{mention}}`
