### ISSUE TITLE
[Autoroom] discord.errors.HTTPException: 400 Bad Request (error code: 40032): Target user is not connected to voice.

### ISSUE THREAD

**Issue by ocformula** [PhasecoreX/PCXCogs#119]
If a user enters the autoroom source, a new voice channel is created, and the user in the autoroom source exits the autoroom source before being moved to the new voice channel, an error occurs.

 6월 03 19:51:17 clr-live python[315]:   File "/home/discordbot/.local/share/Red-DiscordBot/data/red/cogs/CogManager/cogs/autoroom/autoroom.py", line 447, in _process_autoroom_create
 6월 03 19:51:17 clr-live python[315]:     await member.move_to(
 6월 03 19:51:17 clr-live python[315]:   File "/home/discordbot/redenv/lib/python3.11/site-packages/discord/member.py", line 966, in move_to
 6월 03 19:51:17 clr-live python[315]:     await self.edit(voice_channel=channel, reason=reason)
 6월 03 19:51:17 clr-live python[315]:   File "/home/discordbot/redenv/lib/python3.11/site-packages/discord/member.py", line 906, in edit
 6월 03 19:51:17 clr-live python[315]:     data = await http.edit_member(guild_id, self.id, reason=reason, **payload)
 6월 03 19:51:17 clr-live python[315]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 6월 03 19:51:17 clr-live python[315]:   File "/home/discordbot/redenv/lib/python3.11/site-packages/discord/http.py", line 744, in request
 6월 03 19:51:17 clr-live python[315]:     raise HTTPException(response, data)
 6월 03 19:51:17 clr-live python[315]: discord.errors.HTTPException: 400 Bad Request (error code: 40032): Target user is not connected to voice.

```
        await member.move_to(
            new_voice_channel, reason="AutoRoom: Move user to new AutoRoom."
        )
```

So I modified the code and it seems to be working fine for now.

```
        try:
            await member.move_to(
                    new_voice_channel, reason="AutoRoom: Move user to new AutoRoom."
            )
        except discord.errors.HTTPException:
            await self._process_autoroom_delete(new_voice_channel)
            await self.config.channel(new_voice_channel).clear()
```            

I'm not a developer.
I can't predict how this code I modified will cause your bot to function incorrectly.

**Comment by PhasecoreX** [comment]
Fixed this with 1d07ad6bd19769114d8980b4bad4f679dac4d698, thank you!
