### ISSUE TITLE
[Autoroom][Request]Claim Ownership w/ Cooldown/Mod&Admin Claim Ownership

### ISSUE THREAD

**Issue by LifelessMagoo** [PhasecoreX/PCXCogs#121]
Hello!

Wondering if you wouldn't mind adding the ability for users to take over an autoroom after a specified amount of time w/o the owner being present; and those with the designated admin/mod roles can tale over an autoroom at any time.

Thank you so much!

**Comment by PhasecoreX** [comment]
Added this with 1d07ad6bd19769114d8980b4bad4f679dac4d698, please give it a try and let me know if I missed anything!
