### ISSUE TITLE
Autoroom requires python 3.11 while RedBot requires python3.10

### ISSUE THREAD

**Issue by twilwa** [PhasecoreX/PCXCogs#136]
![image](https://github.com/PhasecoreX/PCXCogs/assets/111034762/3870ab38-ba23-48af-8229-5eb1d3cd0cd9)
if you weren't aware

**Comment by PhasecoreX** [comment]
Redbot doesn't require 3.10, that's just what Ubuntu 22.04 uses. Redbot can run with anything from 3.8 to 3.11.

For Ubuntu 22.04, you can install python 3.11 by getting the deadsnakes ppa and installing it from there:
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.11
```
Take that with a grain of salt, I just looked that up. I don't actually use Ubuntu. But, most results mentioned doing that or compiling it manually.

Or, any Ubuntu newer than 22.04 (non-LTS) will have python 3.11 as default, as well as Debian 12, Fedora, and Arch if you care to switch distros. Or, wait ~5 months for 24.04 LTS to come out, it too should [have python 3.11](https://packages.ubuntu.com/noble/python3.11).
