### ISSUE TITLE
[Autoroom] Feature Request: Permissions Management for created autorooms

### ISSUE THREAD

**Issue by cj2tech** [PhasecoreX/PCXCogs#142]
have the ability for the rooms permissions inherit source category or voice channel. or have the ability set a permissions template,

**Comment by PhasecoreX** [comment]
Created AutoRooms already copy their permissions from the AutoRoom Source, save for a few exceptions, namely the view and manage roles permissions. Check out `[p]autoroomset modify defaults` for more information.

**Comment by cj2tech** [comment]
Yeah that's my issue. I have my discord setup in a way where `@everyone` is very limited until verified.

**Comment by PhasecoreX** [comment]
If a user isn't allowed to see or join the AutoRoom Source, they won't be able to join any AutoRooms it creates, regardless of if it's public/private/etc. So just set up the AutoRoom Source so that only your members (who have the member role of your server) can see it, and everything else should be handled automatically.

**Comment by cj2tech** [comment]
Currently the way I have it configure that is not working for me.

Below is a view of the permissions of the source VC:
![image](https://github.com/PhasecoreX/PCXCogs/assets/9431091/172cd7c6-8860-4793-bbbe-608ab6db8216)


and then this is the room it creates:
![image](https://github.com/PhasecoreX/PCXCogs/assets/9431091/566ede25-37e2-4b67-82ba-89a9636a808b)

I wonder if it matters the fact that I'm using server type.

**Comment by PhasecoreX** [comment]
Can you do `[p]]help AutoRoom` and tell me the cog version, and then do `[p]autoroomset settings` and tell me the settings for your AutoRoom Source? Also if I can see your permissions on the AutoRoom Source for the Bots and Members roles as well.

**Comment by cj2tech** [comment]
Cog Version: 3.7.2 

```
--- Server Settings ---
Admin access all AutoRooms:     [True]
Moderator access all AutoRooms: [True]

--- AutoRoom - Public Lobby ---
Room type:            [Public]
Destination category: [#💬Voice Channels💬]
Room name format:     [Custom: "Public Room {{dupenum}}"]
```

idk what would be the best way to show you the other things other then the pics above

**Comment by PhasecoreX** [comment]
I would expect a "Member Roles" section in those settings if they were detected. Can you verify that the everyone role doesn't have connect permissions in the AutoRoom Source channel, and that your member role does explicitly have the connect permission in the AutoRoom Source?

**Comment by cj2tech** [comment]
I just check it did have can connect on for my everyone. It look like turning that to false fixed it... or possibly the fact I did a hard reboot of the docker server cuz I was getting some random errors on some other apps I was running on the same server along with. Thanks much for help with resolving this.
