### ISSUE TITLE
[RemindMe] Editing option

### ISSUE THREAD

**Issue by Predeactor** [PhasecoreX/PCXCogs#20]
# Description

I would like to see an edit option to the remindme cog, but there is a problem at this:
_Editable_: Time _or_ text

## Solution

The solution is simple. As I saw, variable FUTURE is created when we add a new reminder. This can be used to edit the reminder like it was an identifier, unique to the reminder. Using this identifier, we can edit the reminder.

## Commands

We add the following command:
- [p]reminder edit `identifier` `option` `value`

**Comment by PhasecoreX** [comment]
Yes, I can add this feature, shouldn't be too bad.

The FUTURE variable is a timestamp, so it is not unique. A user could make a reminder for 5 minutes, wait one minute, and then make another for 4 minutes. They would have the same FUTURE value. I already have an ID for each reminder, so I will use that. I will also take the time to improve that reminder ID tracking.

**Comment by Predeactor** [comment]
Thank Phasecore for making the edit command on commit fa47a6b.

**Comment by PhasecoreX** [comment]
Thanks for being patient, this feature addition was a bit of work (preparation + not breaking stuff). Each reminder now should have a unique (to each user) ID, which makes editing and deleting much safer.
