### ISSUE TITLE
[RemindMe] Embeds with links

### ISSUE THREAD

**Issue by Kovaelin** [PhasecoreX/PCXCogs#21]
From a conversation on the support server regarding enhancing the existing embeds.

Unless there is an option to toggle back to plaintext, would it be possible to get link embeds to show up? If that isn't possible, then maybe have a link to the original remindme message inputted by the user, since that message will probably still have the full image/video embed.

Thanks!

**Comment by PhasecoreX** [comment]
Thank you for your patience, I have added a nice jump link to the bottom of the reminder embeds in 8fba68a. All new reminders will have this. Enjoy!
