### ISSUE TITLE
[Remindme] TypeError: error_handler() missing 1 required positional argument: 'fut'

### ISSUE THREAD

**Issue by thisisjvgrace** [PhasecoreX/PCXCogs#22]
Got this in console after latest cog update:

```py
[2020-08-19 01:51:37] [CRITICAL] red.main: Caught unhandled exception in task:
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
TypeError: error_handler() missing 1 required positional argument: 'fut'
```

I believe it's originated from remindme.py#L71 or #L73

My red version: 3.4.0
Discord.py version : 1.4.1
Python version : 3.8.5
OS: Linux Ubuntu 18.04.x x64

**Comment by PhasecoreX** [comment]
This should be fixed now. The reminders were still working regardless, but if any exception somehow came up while it was sending reminders out, then everything would have broken. But now we should be good!

I think once you update the cogs it will still emit the error above one last time (not sure why), but every reload/restart afterwards should be good.
