### ISSUE TITLE
[Wikipedia] support showing images

### ISSUE THREAD

**Issue by thisisjvgrace** [PhasecoreX/PCXCogs#26]
Hi,

I want to request a feature for Wikipedia cog to also display the said wiki article's main image, just like how discord shows it when you post a Wikipedia article link in a channel. I was diving in the code and I can see that you're currently fetching the plaintext version from API and plaintext version does not return any image links iirc. So I am already sweating while writing this because to implement this feature, you will probably need to rewrite some part of the cog to facilitate this but I'm not sure if you would be interested in doing this. Nevertheless, I thought I would open a new issue and give you a high five. 👋 

![Screenshot_20200921-120700_Discord](https://user-images.githubusercontent.com/24418520/93738332-268b8280-fc03-11ea-93f2-4c7b61f47b7e.png)

**Comment by PhasecoreX** [comment]
Today I have learned that the MediaWiki API is a very powerful tool. I was able to add the article thumbnail with ae36aec. Thanks for the suggestion!
