### ISSUE TITLE
autoroom permisisons (Features MAYBE????)

### ISSUE THREAD

**Issue by XxMr1234GamerzxX** [PhasecoreX/PCXCogs#28]
give manage permissions perm on the created channels (Public) so they can manage and control who can join and who can't (make togglable if needed)
also allow for multiple member ranks and default permisisons setups like voice activity Or push to talk stream to room or not

**Comment by PhasecoreX** [comment]
The AutoRoom owner can already use the `[p]autoroom` command to allow and deny users into their room, as well as make their room public or private. If the user had manage permissions, they can seriously screw things up in the server. For example, they can give themselves server mute (or deafen) permissions, and then start server muting everyone for every voice channel. Or they can deny the bot from cleaning up the empty channels. It's too powerful and broad of a permission to give out to everyone, and there is no benefit to having it, so I will not be adding that.

For member ranks, usually there is one role (a member role) that all users have when they agree to the rules or whatever. You're saying that you have certain members who don't have the member role, but you want them to be allowed into the AutoRooms as if they were members?

I have to think about the voice activity/ptt and the stream to room options. In my mind those should be handled by the users role, but I can see where maybe the guild owner would want there to be no streaming except for in an AutoRoom, for example.

**Comment by XxMr1234GamerzxX** [comment]
okay yea which is why i suggested a toggle and/or a default permission config option that allows a admin to give out a default set of permissions defined in some sort of configuration (i'm in no way expecting this to be added over night but it would be nice for flexibility)

i have multiple "member" roles using exclusive roles, so like VIPs and other misc ranks these people don't have a lower rank therefore this feature locks out higher ranking roles from the autorooms so allowing multiple "member roles" is kinda needed tbh as having everyone have the lowest tier rank and stacking all their ranks on top of each other is clunckly and a mess

**Comment by XxMr1234GamerzxX** [comment]
also autoroom doesn't appear to give speak permissions even with [p]autoroom allow <user>

possible fixes: 
add as a default permission on allow 
inherit from category permissions <--- this will also fix my first issue with permissions

**Comment by PhasecoreX** [comment]
No, `[p]autoroom allow` just allows the user to join the room (if they couldn't already). It has nothing to do with being able to speak, as that should be handled by the users role. I guess I'm confused by your roles setup. This makes it seem like you are denying `@everyone` role from speaking in the whole guild, but then also all of your member roles aren't allowed to speak either?

Adding clone channels could make this whole cog needlessly complex and break other features, but also adding configurations for each and every permission is also complex. Let me know how your guild and its roles are set up and I'll decide on a path forward.

**Comment by PhasecoreX** [comment]
Just saw your edit (didn't show up in my emails) about your three guilds in one thing. I think it would make more sense to have each guild separate lol. The bot can join multiple guilds after all. Either way, let me know the layout I guess of your guild.

**Comment by XxMr1234GamerzxX** [comment]
i think just copying the category/or fallback on main perms would just be better only saying due to thats how autorooms handles that kind of thing im already using their system
im guild has a community section which contains the autorooms 
a bot section s other people can use my bot if they wish with invites and syntax
games hosting company and all support/channels releated
minecraft network with chat channels and dynamic voice channels 
games development company with related channels

**Comment by PhasecoreX** [comment]
With the latest update I have added the functionality to add multiple member roles. Additionally, these member roles are saved per AutoRoom Source, so you can for example have a source only allowing member group 1, another source only allowing member group 2, and a third source that allows group 1 and 2.

Once you update check out `[p]autoroomset settings` to see the current settings for member roles per AutoRoom Source, and `[p]autoroomset modify memberrole` to add and remove member roles for an AutoRoom Source.

This will still allow the AutoRoom owner the same control they had previously over their AutoRoom (private/public/allow/deny/etc.)

**Comment by XxMr1234GamerzxX** [comment]
oh thats cool nice work!

**Comment by HelmicNewciv** [comment]
Running into similar issues.  Because autorooms don't have a way to set their default permissions (ie, cloning it from the parent room), it leads to situations like autorooms being universally unable to let anyone stream, force push-to-talk, et cetera unless their role allows it globally.  Which then makes it hard to make channels that have slightly different tweaks based on different use cases.

The owner of the room doesn't necessarily need a way to change the channel permissions themselves, but something like streaming rooms or PTT-only rooms would need to have some way to have those settings applied.

**Comment by PhasecoreX** [comment]
With 9f0faeb I have added the functionality that `@everyone` perms will be copied from the AutoRoom Source to the new AutoRoom. This, along with multiple member roles per AutoRoom Source, should completely solve this issue, unless I missed something. Let me know if something broke!

For example, you can deny voice activity in the AutoRoom Source, which will make all AutoRooms it creates be push to talk. Or you can allow video in the AutoRoom Source, which will allow users in AutoRooms to stream.

**Comment by HelmicNewciv** [comment]
Just wanting to say this has been working perfectly, people love it.

**Comment by PhasecoreX** [comment]
I'm glad to hear it! I haven't heard anyone have issues with it either; I'm glad I didn't break anything :+1:
