### ISSUE TITLE
More Ban Lists

### ISSUE THREAD

**Issue by PhasecoreX** [PhasecoreX/PCXCogs#3]
Currently, the plugin is useless, since its only source of ban info is down at the moment. Research is needed to look into if there are other public lists we can add to this plugin.

Or, maybe we can make our own global ban list?

**Comment by MayhemBill** [comment]
Talked with the guys behind discord.services, they have shut down completely. and to my searches a few others exists. 

https://disboard.org/servers/tag/banlist there are currently 2 on this list.

**Comment by Kovaelin** [comment]
This one seems to be active. https://www.globan.xyz/banlist

**Comment by MayhemBill** [comment]
they are active, I'm in the discord, as of right now there is a closed beta API, not sure when they will actually open it to public.

**Comment by PhasecoreX** [comment]
Thanks for the suggestions, and the info on discord.services! There is also https://api.ksoft.si/ that I am looking into as well. I'll get to making a modular system that bot owners can pick and choose which banlists they would like to check (via setting api keys). I'll probably start with this one (as they have an API already that I can hit), then check out globan, then any others.

**Comment by MayhemBill** [comment]
Ksoft was offline when I checked last time, so I didn't really look into it, but they look like a more promising ban list, the downside is they require a token that seems to be approved on a manual check basis. So each user would need their own token. I would definitely like to see the options of choosing banlists as well.

**Comment by PhasecoreX** [comment]
Okay with commit 1a65439, I have refactored a large portion of the BanCheck plugin so that it can support multiple checks and easy enabling/disabling of services (also ease of adding future services). I was able to create the Globan one solely based off of one example call in their Discord, and the KSoft.Si one is based off of their docs.

Once I get an actual API token for these, I will make sure that they work as intended, and hopefully fix them in a timely manner.

**Comment by PhasecoreX** [comment]
Alright finally got a KSoft.Si API key! There were some errors in how I was calling the service, which are now fixed. That should be everything now for these two services! Let me know if I missed anything. If there is another service to implement, just open another issue. Thanks!
