### ISSUE TITLE
[AutoRoom] Associated text channel

### ISSUE THREAD

**Issue by sulizi** [PhasecoreX/PCXCogs#30]
It'd be nice to have an associated text channel created in the category set when a user makes a room (x's room, x's text room). Sometimes a user doesn't prefer to or can't talk, and having one "global" voice text channel can get messy fast when many autorooms are being created.

**Comment by PhasecoreX** [comment]
With 04f4670 this should be added. Check out `[p]autoroomset modify text <autoroom_source>` to set it up per AutoRoom Source. This feature was big, and also went out with a code refactoring so if anything isn't working correctly feel free to reopen this issue!
