### ISSUE TITLE
Autoroom: Save custom channel name per user

### ISSUE THREAD

**Issue by IceFlom** [PhasecoreX/PCXCogs#37]
The following enhancement would be great:

If a user modifies the name of his own channel, autoroom is saving this new name for the user. When the user comes back and creates a new autoroom, the old custom name should be used as default. If there is no entry for that user, then autoroom will use the default settings (custom, game, name).

**Comment by PhasecoreX** [comment]
I've thought about this for a while (clearly, sorry about that) and I don't think this would be a great fit for the AutoRoom cog. It's easy enough for a user to quickly paste in a room name if they need it, and that avoids any headaches of users not understanding that their previous room name is going to show up every time (even if they renamed it thinking it would be temporary). I'd have to be storing every room name for every user in every AutoRoom Source, as well as add some sort of a command to reset that users custom name for an AutoRoom Source, and then the users need to be smart enough to actually use that command. A lot of overhead for not much gain, and potentially the confusion of the end user.

Plus, if a user wants some custom room name every time, and it's generic enough that others wouldn't mind it, maybe [the new default room name template system](https://github.com/PhasecoreX/PCXCogs/blob/master/autoroom/README.md#templates) can help you out.
