### ISSUE TITLE
Autoroom: New toggle for "live game update" (channel name)

### ISSUE THREAD

**Issue by IceFlom** [PhasecoreX/PCXCogs#38]
Another suggestion:

A new toggle to activate "live game update" for an autoroom source. 
If activated, new channels get the name from the default settings (name, game, custom), like before. As soon as the creator of the channel plays a game, the name of the channel switches to the game's name. If the creator stops playing, the channel get it's old name back or if the creator switches the game, the channel gets the name from the new game.

**Comment by PhasecoreX** [comment]
I like this idea, however channel names are only able to be changed twice every 10 minutes, which is quite a delay. There's potential for a user changing activities and then we would be waiting for up to 10 minutes to change the room name. 10 minutes is a very long time, and at that point the user may think the cog is broken (if they even noticed that it changes the name of their channel automatically). Also, some users might want to customize their AutoRoom name, and after those 10 minutes they just magically lose those changes.

I want all of the interactions with this cog to be quick, easy to use, and predictable for end users. Unfortunately this feature wouldn't be all of those all of the time.
