### ISSUE TITLE
[netspeed.py error]

### ISSUE THREAD

**Issue by Motzumoto** [PhasecoreX/PCXCogs#39]
From the looks of things, i think the import updated? heres the traceback.

```
  File "/home/motz/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/motz/agb-final/Cogs/admin.py", line 296, in netspeed
    s = speedtest.Speedtest(secure=True)
AttributeError: module 'speedtest' has no attribute 'Speedtest'
```

**Comment by PhasecoreX** [comment]
I'm pretty sure there's another cog that uses a different `speedtest` package that is incompatible with this one. Try doing `[p]pipinstall speedtest-cli` and retry the command.

**Comment by Motzumoto** [comment]
> I'm pretty sure there's another cog that uses a different `speedtest` package that is incompatible with this one. Try doing `[p]pipinstall speedtest-cli` and retry the command.

Im only using your netspeed cog, and ive already tried to reinstall reqs

**Comment by PhasecoreX** [comment]
Hmm... I did `[p]cog reinstallreqs` (which took like 9 minutes) and doing `[p]netspeed` still works correctly. The underlying `speedtest-cli` package hasn't been updated in a while either. What other cogs do you have installed?

**Comment by Technetium1** [comment]
I just installed and tested and it's working fine here.

**Comment by Motzumoto** [comment]
Okay I have spent the last couple of hours combing through everything, I only have your netspeed cog installed. I don't know why it's not working

**Comment by Technetium1** [comment]
@Motzumoto If you run speedtest-cli in a shell (from `just download` section [here](https://pypi.org/project/speedtest-cli/)) does it give normal results? I have had issues in the past getting speedtest-cli to work on memory starved systems. If you have any issue there, does it complete with `speedtest-cli --no-pre-allocate`?

**Comment by Motzumoto** [comment]
> @Motzumoto If you run speedtest-cli in a shell (from `just download` section [here](https://pypi.org/project/speedtest-cli/)) does it give normal results? I have had issues in the past getting speedtest-cli to work on memory starved systems. If you have any issue there, does it complete with `speedtest-cli --no-pre-allocate`?

You cool if I test tomorrow? it's currently midnight

**Comment by Motzumoto** [comment]
Okay, so for some reason it started working again. I'm not sure why because i actually didnt do anything different but yknow, it be like that i guess
