### ISSUE TITLE
autoroom: welcome message with informations how to allow people in private rooms

### ISSUE THREAD

**Issue by luxus** [PhasecoreX/PCXCogs#40]
hey, 
at the moment the message from the bot in the textchannel of the room:
luxus, this is your own text channel that anyone in your AutoRoom can use.

maybe it would be nice if it would give informations how to allow people in a private room

**Comment by PhasecoreX** [comment]
Yes, I'm working on a feature to allow changing that message. By default it won't send anything, and can be enabled to send whatever is wanted.

**Comment by PhasecoreX** [comment]
Took awhile, but c6103c7 solves this. Check out `[p]autoroomset modify text hint` to set up a custom hint message to send on text channel creation.
