### ISSUE TITLE
[reactchannel] Option to enable only for text or only for images

### ISSUE THREAD

**Issue by Merp-Me** [PhasecoreX/PCXCogs#48]
Being able to choose what types of messages the bot will react to will be useful. If there is a community art channel and people provide feedback, it would be annoying for every message to get the upvote and downvote emoji reacted to it

**Comment by PhasecoreX** [comment]
ReactChannel is in need of a complete rewrite at some point. When I do this, I will keep this in mind. There are many issues and many niche use cases that I never imagined, so I need to rewrite it to be more general and customizable. Then adding something like this will be more manageable.

**Comment by PhasecoreX** [comment]
Sorry this took quite a while, but with the latest update, you can now use filters to choose what types of messages get reacted to.

Types of filters include `commands`, `text`, and `images`. So for you, it would be as simple as `[p]reactchannelset filter content text #your_vote_channel` to disable reacting to text (commands are already ignored by default). Then only images will be reacted to.

Enjoy!
