### ISSUE TITLE
[DecodeBinary] Request

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [PhasecoreX/PCXCogs#5]
Hello, for decodebinary I would like to request that you make it so that it doesn't error out (in console) if the bot is missing perms in a server, as my bot and others peoples bots are in servers that we (the owner of the bot) are not in where we can't control the permissions of the bot.

**Comment by PhasecoreX** [comment]
The latest cog update should fix this so that when a bot doesn't have permission to send in a channel, it will silently fail. If I missed some errors that are still appearing, let me know which ones and possibly what permissions the bot is lacking in those channels so I can reproduce it. Thanks!
