### ISSUE TITLE
[FEATURE] [Autoroom] Add possibility to create a list of custom names for autorooms

### ISSUE THREAD

**Issue by IceFlom** [PhasecoreX/PCXCogs#50]
Type: FEATURE REQUEST
Cog: Autoroom

I would like to have the possibility to add a list of custom names to an autoroom source. A new room created from this source should get one name from this list randomly.

**Comment by PhasecoreX** [comment]
Sorry it took like 4 years, but if you're still interested, we switched over to jinja2 for the template rendering. That should allow you to do something like this:
```
{{ ["This is", "This isn't", "This could be"] | random }} your AutoRoom
```
It'll pick one of those 3 options in the list randomly to build the AutoRoom name.

You'd modify the default name of an AutoRoom like so:
```
[p]autoroomset modify name custom <autoroom_id> {{ ["This is", "This isn't", "This could be"] | random }} your AutoRoom
```
Again, sorry it took so long. Enjoy!
