### ISSUE TITLE
[Suggestion - Autoroom] Source Roles Copy

### ISSUE THREAD

**Issue by LifelessMagoo** [PhasecoreX/PCXCogs#54]
Would love to see roles & their permissions in addtion to the @everyone role copied over from the autoroom source! I have a banned from vc video role that I can't seem to apply to the generated autorooms.

Thank you! Love the cog otherwise, best one available :-)

**Comment by PhasecoreX** [comment]
Thanks! Really appreciate it!

Can you do `[p]autoroomset permissions`? It should be copying every permission from every role (and user) on the AutoRoom source to the created AutoRoom. Basically a clone of the AutoRoom Source with a few modifications.

**Comment by LifelessMagoo** [comment]
![SmartSelect_20210927-090322_Discord](https://user-images.githubusercontent.com/75867173/134924177-b505b70f-da62-428f-bf67-95326f27479b.jpg)
![SmartSelect_20210927-090300_Discord](https://user-images.githubusercontent.com/75867173/134924179-d41535ef-a807-4f6d-a64b-3595b737b884.jpg)

It says everything is cool, here's the permissions of a newly generated autoroom too.

**Comment by LifelessMagoo** [comment]
Autoroom source: 
![SmartSelect_20210927-090556_Discord](https://user-images.githubusercontent.com/75867173/134924501-b56b4a31-bf44-44af-9505-8c7fef3afc67.jpg)

**Comment by PhasecoreX** [comment]
Are you using the latest version of the cog? That "Everything looks good here!" should be above the permissions list, not at the bottom.

**Comment by LifelessMagoo** [comment]
I believe so, I just ran the update command for all my cogs the other day. Just ran it again and it was not updated.

**Comment by LifelessMagoo** [comment]
Just reinstalled the cog and it worked! Thanks for your help!! <3
