### ISSUE TITLE
[Bug] (netspeed) lib broken probably 

### ISSUE THREAD

**Issue by Motzumoto** [PhasecoreX/PCXCogs#73]
speed_test = speedtest.Speedtest(secure=True)
AttributeError: module 'speedtest' has no attribute 'Speedtest'

**Comment by PhasecoreX** [comment]
Do you, or did you have the PredaaA fork of SpeedTest cog? That one uses Ookla's speedtest package, which isn't compatible with the one used here (speedtest-cli).
You will need to remove that cog, along with Ookla's speedtest package, and then you can reinstall this cog and it should download the correct speedtest-cli library.

**Comment by Motzumoto** [comment]
> Do you, or did you have the PredaaA fork of SpeedTest cog? That one uses Ookla's speedtest package, which isn't compatible with the one used here (speedtest-cli). You will need to remove that cog, along with Ookla's speedtest package, and then you can reinstall this cog and it should download the correct speedtest-cli library.

I entirely reinstalled the package and cog and im still getting this error 

```py
    speed_test = speedtest.Speedtest(secure=True)
AttributeError: module 'speedtest' has no attribute 'Speedtest'

**Comment by Motzumoto** [comment]
I love when even after restarting once that doesnt fix it so you do it again and it gets fixed
