### ISSUE TITLE
Autoroom: Add option to automatically print help text in newly created text channels.

### ISSUE THREAD

**Issue by Flightkick** [PhasecoreX/PCXCogs#74]
This feature would provide some easy-to-access documentation to end-users for managing their channels.
It could be the same message that `[p]autoroom` displays.

**Comment by PhasecoreX** [comment]
You can set this up by using `[p]autoroomset modify text hint`, unless you mean something else? With that command you can set up a message that is sent to every AutoRoom Text Channel when it is created. You could put your own welcome text, listing some of the important commands, or directing the user to look at the `[p]autoroom` command.

**Comment by Flightkick** [comment]
That will do, thanks!
