### ISSUE TITLE
[Autoroom] support slash commands

### ISSUE THREAD

**Issue by Zaphkeil** [PhasecoreX/PCXCogs#79]
Is the autoroom support slash commands? I try to use https://github.com/phenom4n4n/phen-cogs to add slash commands but I don't know how to use it.

**Comment by PhasecoreX** [comment]
Natively, none of my cogs support slash commands. Once Red-DiscordBot supports them, I will consider adding them. I do not know anything about that slashtags cog. If you get it working then cool, but I'm not going to provide support for it.
