### ISSUE TITLE
[BUG] [reactchannel] Cog not loading

### ISSUE THREAD

**Issue by MichaelCoding25** [PhasecoreX/PCXCogs#84]
Since either the commits on May 27th or the commit on June 2nd, the cog was not able to load after I did the `%cog update`, then I attempted to manually `%load reactchannel` and it still did not work and put out this error: https://i.imgur.com/h5C4ezi.png.

Console Screenshot: https://i.imgur.com/t4QWNz4.png

Seems to indicate the issue is in the `_list_roles` function.

Info:
- Current Red Version: 3.4.17
- Current Python version: 3.8.13

**Comment by PhasecoreX** [comment]
Sorry about that, should be good now!
