### ISSUE TITLE
[AutoRoom] Add an option to always deny send message permissions

### ISSUE THREAD

**Issue by EternalllZM** [PhasecoreX/PCXCogs#85]
For context [this was the conversation on Discord](https://discord.com/channels/240154543684321280/240212783503900673/988999669591990303) regarding the send-messages permission being automatically enabled and not being carried over from the source channel. 

The reasoning behind this behavior is solid unless we factor in the forceful push of TIV by Discord and the inability to disable it due to aforementioned behavior. Your only option is to allow TIV (dangerous if you use Red for automoderation) or disable Autoroom entirely and use manual channels + send message deny override.

**Comment by PhasecoreX** [comment]
Hey! Sorry this took 2 years to implement. If you're still interested, I've added this to AutoRoom.

Check out `[p]autoroomset modify specialperms sendmessage` to control the send message permission on newly created AutoRooms.

Again, sorry it took so long.
