### ISSUE TITLE
[Feature Request] Allow everyone to join autorooms where the source room is only accessible to a certain role.

### ISSUE THREAD

**Issue by pizzanakin** [PhasecoreX/PCXCogs#95]
Currently, if a user creates an autoroom from a source room, only members who have access to the source room can be allowed to join the generated autoroom.

I have been asked to make a set up for tiered voice channels, where users with specific roles can create an autoroom, but then allow all members of the server to join it. 

It would be awesome if that functionality could be added to this cog so that I can keep using it on the server I'm working for.

**Comment by PhasecoreX** [comment]
Should be available with commit fb8029f

Setting the AutoRoom Source permissions for the `@everyone` role to deny view, and then for your specific role to allow view, will allow the special role to make AutoRooms, but everyone else will only be able to join the created ones.

If you had member roles, you'd deny everything for the `@everyone` role, then your member role would be allow connect and deny view channel, then your special role would be allow view channel and connect.

Public/locked/private/server AutoRoom types should all work as expected with the resulting AutoRooms.

If I screwed anything up, let me know!

**Comment by pizzanakin** [comment]
Thanks so much for working on this!

How exactly would I go about updating the cog to make sure the new commit
is added?
Sorry for this basic question, I am still a bit new to using Redbot for
Discord.
I have tried uninstalling and installing the cog, but I am not sure if that
did it.

Right now I have set the permissions for my autoroom source for @everyone
to deny viewing but allow connecting.
When an autoroom gets generated, it doesn't become visible to @everyone
though. So I probably don't have the new update yet.

Could you help me out on this? Thanks in advance!

**Comment by PhasecoreX** [comment]
Sure, you just have to do `[p]cog update`, then it'll ask you to reload the updated cogs. Then you should be up to date!
