### ISSUE TITLE
bancheck new api

### ISSUE THREAD

**Issue by scottoss** [PhasecoreX/PCXCogs#96]
https://api.antiraid.win/

https://api.antiraid.win/stats                                                 -- Grabs the api statistics
https://api.antiraid.win/cases/CASE_ID_HERE                       -- Grabs a provided case
https://api.antiraid.win/bans/USER_ID_HERE                        -- Grabs a banned user

**Comment by scottoss** [comment]
banned user id for example: 244261481049358336

**Comment by PhasecoreX** [comment]
Added with 0ab9f6b5adae7ef21327c7382150790c55a0355d
